#
b !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Schema Area":6,32;1 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Info Area":7,32;1 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Customer/Order Area":8,32;8 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Primary Index Area":9,1;8 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Customer Index Area":10,1;64 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
#
d "Order Index Area":11,32;64 !"D:\2015-00-DEV\Study\Study-Progress\01 - Progress DCA\Base\"
